# 
# makefile for rt-usb
#
#  (c) 2008-2016 Copyright Eckler Software
#
# Author: David Suffield, dsuffiel@ecklersoft.com
#
# Notes:
# The pic16f1459 has 32 data banks.
#
# History:
# Version 0.35,  des 02/20/2016   Added winusb.sys support using Microsoft OS Descriptors.
# Version 0.36,  des 02/28/2016   Tested ok with Windows 10 Pro. No .inf file needed.
# Version 0.1,   des 09/04/2016   Repurposed from pic18f2455 to pic16f1459.
# Version 0.2,   des 09/09/2016   Clean compile with SDCC 3.6.0 for pic18f2455.
# Version 0.3,   des 09/11/2016   Pic18f2455 works ok with SDCC 3.6.0. Good release for 18f2455.
# Version 0.4,   des 09/13/2016   Pic16f1459 new.
# Version 0.6,   des 09/19/2016   Pic16f1459 compiles ok.
# Version 0.7,   des 10/02/2016   Changed USB dual-port ram to CPU banked address instead of linear.
# Version 0.7.1, des 10/15/2016   Pic16f1459 has 32 data banks. Banks 0-6 are used by the usb dual port ram. I manually located
#                                 global data to unused data bank 7 otherwise the sdcc linker would map the global data to the 
#                                 dual port ram. Data defined as static and "near char*" pointers were not a problem. The 
#                                 linker would map that data correctly to upper unused data banks. Now the 16f1459
#                                 enumerates correctly.
# Version 0.7.5, des 10/16/2016   Code cleanup, removed usbmmap.c, went from 6 to 5 *.c files. Tried going from 6 to 4 *.c files 
#                                 to match 4 code pages, but enumeration failed. 
# Version 0.10,  des 10/16/2016   Committed current code that enumerates ok, but rt-test.py fails. 
# Version 0.11,  des 10/17/2016   Enabled BOR, now powerup reset works ok. Without BOR powerup only worked with Pickit3 plugged in. 
# Version 0.13,  des 10/22/2016   Started conversion to xc8 compiler. Sdcc works ok for 18f pics but not 16f pics. For the 16f1459 
#                                 sdcc linker could not reserve the usb dualport ram for the program. The linker would allocate sdcc 
#                                 library data in the dualport data area thus causing memory conflicts.
# Version 0.14,  des 10/23/2016   Rt-test works ok with new xc8 compiler. TODO: 1) read new INPUTn bits 2) new OUTPUTn commands.  
# Version 0.15,  des 10/24/2016   INPUTn now work ok. Added command support for OUTPUTn. TODO: if possible recover from usb suspend.
# Version 0.16,  des 10/25/2016   Usb suspend/recover works ok. TODO: hook up DB25 and run dongle test.
# Version 0.17,  des 11/13/2016   Swapped pins for OUTPUT0 and OUTPUT1 which matches the schematic.
# Version 0.18,  des 12/04/2016   Minor cleanup disable analog input for RA4 on power up. 
# Version 0.20,  des 06/30/2017   Removed stall count logic, added INPUT0 frequency counter. 
# Version 0.21,  des 08/01/2017   Calibrated LFINTOSC and added STEP_CAL_QUERY command.
# Version 0.22,  des 08/02/2017   Removed LFINTOSC calibration and timer1 code. INPUT0 measurment works ok with timer0 only.
# Version 0.23,  des 10/16/2017   Add sync_start command. Debounced INPUT0 index pulse detection.
#

VERSION := 0.23
INSTALLDIR := /usr/bin
PROJECT := rtusb_pic16f

CHIP := 16f1459
CC := /opt/microchip/xc8/v1.38/bin/xc8
FLAGS := --chip=$(CHIP) -Q
SIZE := size

CFILES := main.c usbdrv.c usbctrltrf.c usb9.c usbdsc.c
HFILES := typedefs.h usb9.h usbcfg.h usbctrltrf.h usbdrv.h usbdsc.h usb.h
OBJS := $(CFILES:.c=.p1) 

all: $(PROJECT).hex script

%.p1: %.c $(HFILES) makefile
	$(CC) $(FLAGS) --pass1 $<

# Reserve the usb dualport ram for the program.
%.hex: $(OBJS) 
	$(CC) $(FLAGS) --RAM=default,-020-06f,-0a0-0ef,-120-16f,-1a0-1ef,-220-26f,-2a0-2ef,-320-32f -O$@ -M --ASMLIST $(OBJS)
	$(SIZE) $@

clean:
	rm -f *.as *.lst *.cof *.cmf *.d *.obj *.hex *.map *.hxl *.rlf *.sdb *.sym *.pre *.p1 *~ 

# A “Program succeeded” message displays after programming is complete. A verify is
# automatically performed during a programming sequence.
script:
	@echo "# This file is generated by the makefile, do NOT edit." > mdb_script; \
	echo "Device pic$(CHIP)" >> mdb_script; \
	echo "set system.disableerrormsg true" >> mdb_script; \
	echo "Hwtool pickit3 -p" >> mdb_script; \
	echo "Program ./$(PROJECT).hex" >> mdb_script; \
	echo "sleep 1500" >> mdb_script; \
	echo "Quit" >> mdb_script

# Flashing requires Pickit3 and usb cable plugged in for power. 
flash:
	/opt/microchip/mplabx/v3.40/mplab_ide/bin/mdb.sh mdb_script

dist:
	rm -fr $(PROJECT)-$(VERSION)
	mkdir $(PROJECT)-$(VERSION)
	cp $(CFILES) $(HFILES) makefile doxyfile $(PROJECT)-$(VERSION)
	tar czvf $(PROJECT)-$(VERSION).tar.gz $(PROJECT)-$(VERSION)
	rm -r $(PROJECT)-$(VERSION)

# Do not delete intermediate files.
.PRECIOUS: %.p1

.PHONY: clean flash dist
